### PR TITLE
Add the Zenodo/DOI badge

### LINKED ISSUE #90: DOI integration
The Zenodo DOI is now set up with twitcher! 

In order to get the ball rolling, there needs to be a tagged release at some point. Once that has happened, we can add the DOI badge to the README.

### PR DESCRIPTION
**Pull request by Zeitsperre**
Closes #90

### CODE REVIEW

**Comment by fmigneault** [comment]
Is there a clean/better way to update the DOI ID in the URL for different versions? 
As per https://github.com/bird-house/twitcher/issues/90#issuecomment-893562076, Twitcher 0.5.3 is used in birdhouse-deploy. 
It looks like each tag generates a new DOI reference, which will be a pain (an easy to forget) update each time we tag a new version.

**Comment by Zeitsperre** [comment]
Hey Francis! There is indeed a way of pointing to a specific release version. If we want to make a static link to the v0.5.3 release, we can use the static DOI badge for that particular version:
```
.. image:: https://zenodo.org/badge/DOI/10.5281/zenodo.3736115.svg
   :target: https://doi.org/10.5281/zenodo.3736115
   :alt: Zenodo DOI
```

If that works for you, I can modify my PR here.

**Review by huard — APPROVED** [review]

**Comment by Zeitsperre** [comment]
@fmigneault Would you like the fixed or floating version of the DOI badge to show?

**Comment by fmigneault** [comment]
@Zeitsperre 
It would be great to have an URL that uses the version number directly, because it could be added to bumpversion `setup.cfg` settings and we would never have to worry about changing the URL manually in the README with auto-update. 

I don't see how (if?) it is possible to automatically obtain the zenodo `3736115` number that would be generated from a new tag version.

**Comment by Zeitsperre** [comment]
@fmigneault 

Looked into this, and it seems like [it's never going to happen](https://www.openaire.eu/blogs/zenodo-now-supports-doi-versioning-1):

**Why don’t the DOIs have a version number suffix like “.v1”?**
_Including semantic information such as the version number in a DOI is bad practice, because this information may change over time, while DOIs must remain persistent and should not change. Moveover, Zenodo DOI versioning is linear, which means that the Zenodo version number may in fact not be the real version number of the resource. Take for instance software, where it is common practice to have dot versions and make new releases in a non-linear order (e.g. first v1.0, then v1.1, then v2.0, then v1.2). The versioning suffix is also not a functionality of the DOI system, i.e. adding .v2 to DOI will not resolve to version 2 of a resource for any DOI from any provider. Different providers also uses different patterns such as e.g. .v2, .2, /2. Most importantly, version suffixes are not machine readable. A discovery system that understands DOIs, will not know that .v1 and .v2 of a DOI are in fact two versions of the same resource. A better solution to this problem is to semantically link two DOIs in the metadata of a DOI. This ensures that discovery systems have a machine readable way to discover that two DOIs are versions of the same resource._

We can point to the proper version manually, but automating the process would be quite the challenge. Not sure how you want to proceed.

**Comment by fmigneault** [comment]
@Zeitsperre 
Maybe look into the "Concept DOI" feature described on the same page: 
> Where does the Concept DOI resolve to?
Currently the Concept DOI resolves to the landing page of the latest version of your record. This is not fully correct, and in the future we will change this to create a landing page specifically representing all of the versions.

If we can "link" all twitcher related DOI/version together, the static URL of the concept could be used in the readme.

**Comment by fmigneault** [comment]
Found it: `10.5281/zenodo.3736114` 
In the "Versions" box. 
It redirects to v0.6.0 at the moment when clicked.

**Comment by Zeitsperre** [comment]
Ah, I underastand what you mean now. I can update this URL to use the concept DOI on this project and if you want to publish something specific to a loadout of Twitcher, you can point to versions using specific/static DOIs.

**Review by fmigneault — APPROVED** [review]

**Pull request merged**
