### PR TITLE
Http status codes

### PR DESCRIPTION
**Pull request by fmigneault**
When raising any `OWSException`, the returned response actually always indicate `200` which is confusing in case of unauthorized or bad requests cases.

This PR fixes this by making forbidden services have `401` (unauthorized), missing parameters have `400` (bad request), missing service `404` (not found), ect. The XML body is untouched.

`OWSException` can set `status_base` directly in the class definition, or pass it as input parameter when raised for custom status code for a given specific case. The value can be any of the int status code, the HTTPException type, or an HTTPException instance.

### CODE REVIEW

**Comment by cehbrecht** [comment]
Test failed because PR is missing #83.

**Comment by cehbrecht** [comment]
@fmigneault merged. Thanks :)

**Comment by fmigneault** [comment]
@cehbrecht do you mind if I tag it as 0.5.2?
It will be useful for a current project on our side.

**Comment by cehbrecht** [comment]
@fmigneault sure, go ahead.

**Pull request merged**
