### PR TITLE
avoid traceback on log owsexception

### PR DESCRIPTION
**Pull request by fmigneault**
Because the raised OWSException derives from Exception, logger.exception automatically resolves the exc_info and dumps the traceback. 
In this case, it is a valid 'security check failed', not an error. So simply emit a warning instead to avoid confusion with "breaking code".

Can also be merged to master, but I would like to stay on `0.5.x` version for now as I haven't implemented/tested complete compatibility with more recent changes and Magpie.

### CODE REVIEW

**Comment by cehbrecht** [comment]
@fmigneault should I cherry-pick this PR to master?

**Comment by cehbrecht** [comment]
@fmigneault merged. thanks :)

**Comment by fmigneault** [comment]
Yes, you can add it to master too. Thanks

**Comment by cehbrecht** [comment]
... this code does not exist on master anymore.

**Comment by fmigneault** [comment]
Ok, not a problem.

**Pull request merged**
